# Generated by Django 4.1 on 2022-08-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomanager',
            name='Video_Description',
        ),
        migrations.AddField(
            model_name='videomanager',
            name='parent_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.titlemanager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videomanager',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='videomanager',
            name='video_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
